// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIOxDhAz9AcR8i9xGpvgMf1eNkwWjuaOw',
    appId: '1:164909332735:web:10f75e38131f5c79bd34ca',
    messagingSenderId: '164909332735',
    projectId: 'sehealthyapp',
    authDomain: 'sehealthyapp.firebaseapp.com',
    storageBucket: 'sehealthyapp.firebasestorage.app',
    measurementId: 'G-2WRZWBE5XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-UnJR7s7qf10OaOMzL9DO7oyLlc_cYT8',
    appId: '1:164909332735:android:69761b090933267fbd34ca',
    messagingSenderId: '164909332735',
    projectId: 'sehealthyapp',
    storageBucket: 'sehealthyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7p324e7GbrPOw9U5RLOAzcPrQeor3eUc',
    appId: '1:164909332735:ios:2fd77d218541a347bd34ca',
    messagingSenderId: '164909332735',
    projectId: 'sehealthyapp',
    storageBucket: 'sehealthyapp.firebasestorage.app',
    iosBundleId: 'com.example.sehealthyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7p324e7GbrPOw9U5RLOAzcPrQeor3eUc',
    appId: '1:164909332735:ios:2fd77d218541a347bd34ca',
    messagingSenderId: '164909332735',
    projectId: 'sehealthyapp',
    storageBucket: 'sehealthyapp.firebasestorage.app',
    iosBundleId: 'com.example.sehealthyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIOxDhAz9AcR8i9xGpvgMf1eNkwWjuaOw',
    appId: '1:164909332735:web:289edc05a7195bd8bd34ca',
    messagingSenderId: '164909332735',
    projectId: 'sehealthyapp',
    authDomain: 'sehealthyapp.firebaseapp.com',
    storageBucket: 'sehealthyapp.firebasestorage.app',
    measurementId: 'G-LD3HY3NJCK',
  );
}
