name: sehealthyapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Tambahkan plugin Firebase Core
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.8
  # firebase_storage: ^11.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
