name: sehealthyapp
description: A new Flutter project.

publish_to: "none" # Private package, not published to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.24.2
  cloud_firestore: ^4.15.6
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.7
  firebase_storage: ^11.6.7
  intl: ^0.18.0
  image_picker: ^1.0.7
  video_player: ^2.4.5

  # UI & icon support
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
