name: sehealthyapp
description: A new Flutter project.

publish_to: 'none' # Private package, not published to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0        # Firestore database
  firebase_auth: ^4.17.7          # Authentication
  firebase_storage: ^11.6.7       # File storage (e.g., image uploads)

  # UI & icon support
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true